name: Generate Consulting Report
on:
  push:
    branches: [main]
jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Clear pip cache
        run: pip cache purge
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Debug directory structure
        run: ls -R
      - name: Run analysis
        working-directory: ./  # Ensure script runs from repository root
        run: python src/report_generator.py
      - name: Commit reports
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add reports/
          git commit -m "Add new consulting report" || echo "No changes to commit"
          git push
